# =============================================================
# Wave Lab Infrastructure - QA
# Jenkins Environment Properties
# =============================================================

# Azure
AZURE_LOCATION=canadacentral
PROJECT_NAME=wave-lab
ENVIRONMENT=qa

# Networking
VNET_ADDRESS_SPACE=10.20.0.0/16
AKS_SUBNET_PREFIX=10.20.1.0/24
PRIVATE_ENDPOINT_SUBNET_PREFIX=10.20.2.0/24

# AKS
AKS_SYSTEM_NODE_VM_SIZE=Standard_D2s_v5
AKS_SYSTEM_NODE_COUNT=2

AKS_USER_NODE_VM_SIZE=Standard_D4s_v5
AKS_USER_NODE_COUNT=2

# Azure Container Registry
ACR_SKU=Premium

# Key Vault
KEY_VAULT_SKU=standard